# Generated by Django 4.2.7 on 2023-11-23 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]

    #In each migration django creates a class of migration and it runs a sql command to the database
    #To see what sql command is being passed run: python3 manage.py sqlmigrate appnamme(here movies) migration_number
    #Example: python3 manage.py sqlmigrate movies 0002


